steps:
  PSTG_MX_SETUP_CONFIGURATION-3579:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85731"
              stepCounter: "3579"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_MX_SETUP_CONFIGURATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "85732"
              stepCounter: "3579"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44897"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85733"
              stepCounter: "3579"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44898"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85734"
              stepCounter: "3579"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44899"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85735"
              stepCounter: "3579"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: MX_SETUP_CONFIGURATION_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44900"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85736"
              stepCounter: "3579"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: MX_SETUP_CONFIGURATION_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44901"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85737"
              stepCounter: "3579"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44902"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85738"
              stepCounter: "3579"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SUBSIDIARY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44903"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85739"
              stepCounter: "3579"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAF_SETUP_CONFIGURATION_FIE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44904"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85740"
              stepCounter: "3579"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: VALUE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44905"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85741"
              stepCounter: "3579"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44906"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85742"
              stepCounter: "3579"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44907"
                    stepCounter: "2734"
                transform: ""
          - columnReference:
              columnCounter: "85743"
              stepCounter: "3579"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "44908"
                    stepCounter: "2734"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85744"
              stepCounter: "3579"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85745"
              stepCounter: "3579"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85746"
              stepCounter: "3579"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85747"
              stepCounter: "3579"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85748"
              stepCounter: "3579"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "85749"
              stepCounter: "3579"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: "85927"
              stepCounter: "3579"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: MX_SETUP_CONFIGURATION
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'MX_SETUP_CONFIGURATION') }} "MX_SETUP_CONFIGURATION"
            name: PSTG_MX_SETUP_CONFIGURATION
            noLinkRefs: []
      name: PSTG_MX_SETUP_CONFIGURATION
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3579"
