steps:
  PSTG_NSPB___ACCOUNT_BALANCE_CONFIG-4231:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105172"
              stepCounter: "4231"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_NSPB___ACCOUNT_BALANCE_CONFIG_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "105173"
              stepCounter: "4231"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CUBE_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45264"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105174"
              stepCounter: "4231"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45265"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105175"
              stepCounter: "4231"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DIMENSION_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45266"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105176"
              stepCounter: "4231"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45267"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105177"
              stepCounter: "4231"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45268"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105178"
              stepCounter: "4231"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: MEMBER_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45269"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105179"
              stepCounter: "4231"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NSPB___ACCOUNT_BALANCE_CONF_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45270"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105180"
              stepCounter: "4231"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: NSPB___ACCOUNT_BALANCE_CONF_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45271"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105181"
              stepCounter: "4231"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45272"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105182"
              stepCounter: "4231"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SHOW_IN_ACCOUNT_BALANCE_PORTL
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45273"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105183"
              stepCounter: "4231"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TYPE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45274"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105184"
              stepCounter: "4231"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45275"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105185"
              stepCounter: "4231"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45276"
                    stepCounter: "2766"
                transform: ""
          - columnReference:
              columnCounter: "105186"
              stepCounter: "4231"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45277"
                    stepCounter: "2766"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105187"
              stepCounter: "4231"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105188"
              stepCounter: "4231"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "107158"
              stepCounter: "4231"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105189"
              stepCounter: "4231"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105190"
              stepCounter: "4231"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105191"
              stepCounter: "4231"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105192"
              stepCounter: "4231"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: NSPB___ACCOUNT_BALANCE_CONFIG
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___ACCOUNT_BALANCE_CONFIG') }} "NSPB___ACCOUNT_BALANCE_CONFIG"
            name: PSTG_NSPB___ACCOUNT_BALANCE_CONFIG
            noLinkRefs: []
      name: PSTG_NSPB___ACCOUNT_BALANCE_CONFIG
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4231"
