steps:
  PSTG_XWS_SHIP_REROUTES-5545:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_ORACLE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190512"
              stepCounter: "5545"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_XWS_SHIP_REROUTES_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "190513"
              stepCounter: "5545"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: SHIP_REROUTE_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184951"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190514"
              stepCounter: "5545"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184952"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190515"
              stepCounter: "5545"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184953"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190516"
              stepCounter: "5545"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PROCESS_STATUS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184954"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190517"
              stepCounter: "5545"
            dataType: VARCHAR(2000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PROCESS_MESSAGE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184955"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190518"
              stepCounter: "5545"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATION_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184956"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190519"
              stepCounter: "5545"
            dataType: VARCHAR(40)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TELEPHONE_NUMBER
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184957"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190520"
              stepCounter: "5545"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184958"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190521"
              stepCounter: "5545"
            dataType: VARCHAR(150)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184959"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190522"
              stepCounter: "5545"
            dataType: VARCHAR(150)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FIRST_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184960"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190523"
              stepCounter: "5545"
            dataType: VARCHAR(60)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: STATE_CODE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184961"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190524"
              stepCounter: "5545"
            dataType: VARCHAR(1000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PUSH_NOTIF_MESSAGE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184962"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190525"
              stepCounter: "5545"
            dataType: VARCHAR(150)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: COMPANY_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184963"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190526"
              stepCounter: "5545"
            dataType: VARCHAR(60)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CITY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184964"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190527"
              stepCounter: "5545"
            dataType: VARCHAR(300)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: EMAIL_ADDRESS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184965"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190528"
              stepCounter: "5545"
            dataType: VARCHAR(60)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: POSTAL_CODE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184966"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190529"
              stepCounter: "5545"
            dataType: VARCHAR(60)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: MIDDLE_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184967"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190530"
              stepCounter: "5545"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PUSH_NOTIF_STATUS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184968"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190531"
              stepCounter: "5545"
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ADDRESS1
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184969"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190532"
              stepCounter: "5545"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SHIP_CONFIRM_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184970"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190533"
              stepCounter: "5545"
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ADDRESS3
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184971"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190534"
              stepCounter: "5545"
            dataType: VARCHAR(60)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: COUNTRY_CODE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184972"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190535"
              stepCounter: "5545"
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ADDRESS2
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184973"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190536"
              stepCounter: "5545"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184974"
                    stepCounter: "5391"
                transform: ""
          - columnReference:
              columnCounter: "190537"
              stepCounter: "5545"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184975"
                    stepCounter: "5391"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190538"
              stepCounter: "5545"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190539"
              stepCounter: "5545"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190540"
              stepCounter: "5545"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190541"
              stepCounter: "5545"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190542"
              stepCounter: "5545"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190543"
              stepCounter: "5545"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190626"
              stepCounter: "5545"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "0"
                    stepCounter: "0"
                transform: "'ORACLE XWS'"
            systemColumnType: None
            transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_ORACLE_XWS
                nodeName: XWS_SHIP_REROUTES
            join:
              joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'XWS_SHIP_REROUTES') }} "XWS_SHIP_REROUTES"
            name: PSTG_XWS_SHIP_REROUTES
            noLinkRefs: []
      name: PSTG_XWS_SHIP_REROUTES
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "5545"
