steps:
  PSTG_EP_QUEUE_SETTINGS-3400:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81181"
              stepCounter: "3400"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_EP_QUEUE_SETTINGS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "81182"
              stepCounter: "3400"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: EP_QUEUE_SETTINGS_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41694"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81183"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: BANK_FILE_CREATION_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41695"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81184"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: BATCH_PROCESSING_DEPLOYMENT_O
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41696"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81185"
              stepCounter: "3400"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41697"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81186"
              stepCounter: "3400"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DEFAULT_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41698"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81187"
              stepCounter: "3400"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: EP_PREFERENCE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41699"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81188"
              stepCounter: "3400"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: EP_QUEUE_SETTINGS_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41700"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81189"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: INSTANT_PAYMENT_PROCESSING_NE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41701"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81190"
              stepCounter: "3400"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41702"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81191"
              stepCounter: "3400"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41703"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81192"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NOTIFICATION_DEPLOYMENT_OLD
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41704"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81193"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NOTIFICATION_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41705"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81194"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_DEPLOYMENT_OLD
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41706"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81195"
              stepCounter: "3400"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41707"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81196"
              stepCounter: "3400"
            dataType: VARCHAR(262136)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PAYMENT_CREATOR_DEPLOYMENT_OL
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41708"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81197"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PAYMENT_PROCESSING_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41709"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81198"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REMOVE_UNPROCESSED_TRANSACTIO
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41710"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81199"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REVERSAL_DEPLOYMENT_OLD
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41711"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81200"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REVERSAL_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41712"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81201"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ROLLBACK_DEPLOYMENT_OLD
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41713"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81202"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ROLLBACK_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41714"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81203"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SCHEDULER_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41715"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81204"
              stepCounter: "3400"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TRANSACTION_MARKING_NEW
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41716"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81205"
              stepCounter: "3400"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41717"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81206"
              stepCounter: "3400"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41718"
                    stepCounter: "2559"
                transform: ""
          - columnReference:
              columnCounter: "81207"
              stepCounter: "3400"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41719"
                    stepCounter: "2559"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81208"
              stepCounter: "3400"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81209"
              stepCounter: "3400"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "83761"
              stepCounter: "3400"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81210"
              stepCounter: "3400"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81211"
              stepCounter: "3400"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81212"
              stepCounter: "3400"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81213"
              stepCounter: "3400"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: EP_QUEUE_SETTINGS
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'EP_QUEUE_SETTINGS') }} "EP_QUEUE_SETTINGS"
            name: PSTG_EP_QUEUE_SETTINGS
            noLinkRefs: []
      name: PSTG_EP_QUEUE_SETTINGS
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3400"
