steps:
  PSTG_ERP_WMS_ROUTES-5532:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_ORACLE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190206"
              stepCounter: "5532"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_ERP_WMS_ROUTES_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "190207"
              stepCounter: "5532"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184694"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190208"
              stepCounter: "5532"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184695"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190209"
              stepCounter: "5532"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SHIP_FROM_ORG_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184696"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190210"
              stepCounter: "5532"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: WMS_ROUTE_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184697"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190211"
              stepCounter: "5532"
            dataType: VARCHAR(80)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FAMILIAR_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184698"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190212"
              stepCounter: "5532"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CARRIER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184699"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190213"
              stepCounter: "5532"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184700"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190214"
              stepCounter: "5532"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184701"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190215"
              stepCounter: "5532"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATION_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184702"
                    stepCounter: "5376"
                transform: ""
          - columnReference:
              columnCounter: "190216"
              stepCounter: "5532"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "184703"
                    stepCounter: "5376"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190217"
              stepCounter: "5532"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190218"
              stepCounter: "5532"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190219"
              stepCounter: "5532"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190220"
              stepCounter: "5532"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190221"
              stepCounter: "5532"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190222"
              stepCounter: "5532"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "190263"
              stepCounter: "5532"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "0"
                    stepCounter: "0"
                transform: "'ORACLE XWS'"
            systemColumnType: None
            transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_ORACLE_XWS
                nodeName: ERP_WMS_ROUTES
            join:
              joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'ERP_WMS_ROUTES') }} "ERP_WMS_ROUTES"
            name: PSTG_ERP_WMS_ROUTES
            noLinkRefs: []
      name: PSTG_ERP_WMS_ROUTES
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "5532"
