steps:
  PSTG_EP_QUEUE_SETTINGS_SUBSIDIARY_MAP-3402:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81226"
              stepCounter: "3402"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_EP_QUEUE_SETTINGS_SUBSIDIARY_MAP_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "81227"
              stepCounter: "3402"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: EP_QUEUE_SETTINGS_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41725"
                    stepCounter: "2561"
                transform: ""
          - columnReference:
              columnCounter: "81228"
              stepCounter: "3402"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: SUBSIDIARY_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41726"
                    stepCounter: "2561"
                transform: ""
          - columnReference:
              columnCounter: "81229"
              stepCounter: "3402"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41727"
                    stepCounter: "2561"
                transform: ""
          - columnReference:
              columnCounter: "81230"
              stepCounter: "3402"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41728"
                    stepCounter: "2561"
                transform: ""
          - columnReference:
              columnCounter: "81231"
              stepCounter: "3402"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41729"
                    stepCounter: "2561"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81232"
              stepCounter: "3402"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81233"
              stepCounter: "3402"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "85758"
              stepCounter: "3402"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81234"
              stepCounter: "3402"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81235"
              stepCounter: "3402"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81236"
              stepCounter: "3402"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81237"
              stepCounter: "3402"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: EP_QUEUE_SETTINGS_SUBSIDIARY_MAP
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'EP_QUEUE_SETTINGS_SUBSIDIARY_MAP') }} "EP_QUEUE_SETTINGS_SUBSIDIARY_MAP"
            name: PSTG_EP_QUEUE_SETTINGS_SUBSIDIARY_MAP
            noLinkRefs: []
      name: PSTG_EP_QUEUE_SETTINGS_SUBSIDIARY_MAP
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3402"
