steps:
  PSTG_BSP_CONFIGURATION_VALUE-3265:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56178"
              stepCounter: "3265"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_BSP_CONFIGURATION_VALUE_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "56179"
              stepCounter: "3265"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: BSP_CONFIGURATION_VALUE_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39547"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56180"
              stepCounter: "3265"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: BSP_CONFIGURATION_VALUE_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39548"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56181"
              stepCounter: "3265"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: BSP_CONFIGURATION_VALUE_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39549"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56182"
              stepCounter: "3265"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CONFIG_VALUE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39550"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56183"
              stepCounter: "3265"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39551"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56184"
              stepCounter: "3265"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FORMAT_PROFILE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39552"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56185"
              stepCounter: "3265"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39553"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56186"
              stepCounter: "3265"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39554"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56187"
              stepCounter: "3265"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39555"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56188"
              stepCounter: "3265"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARSER_PLUGIN_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39556"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56189"
              stepCounter: "3265"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39557"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56190"
              stepCounter: "3265"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39558"
                    stepCounter: "2427"
                transform: ""
          - columnReference:
              columnCounter: "56191"
              stepCounter: "3265"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "39559"
                    stepCounter: "2427"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56192"
              stepCounter: "3265"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56193"
              stepCounter: "3265"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "56396"
              stepCounter: "3265"
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56194"
              stepCounter: "3265"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56195"
              stepCounter: "3265"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56196"
              stepCounter: "3265"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "56197"
              stepCounter: "3265"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: BSP_CONFIGURATION_VALUE
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'BSP_CONFIGURATION_VALUE') }} "BSP_CONFIGURATION_VALUE"
            name: PSTG_BSP_CONFIGURATION_VALUE
            noLinkRefs: []
      name: PSTG_BSP_CONFIGURATION_VALUE
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3265"
