steps:
  PSTG_NSPB___DATA_SOURCE_SETTINGS-4295:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107344"
              stepCounter: "4295"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_NSPB___DATA_SOURCE_SETTINGS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "107345"
              stepCounter: "4295"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: NSPB___DATA_SOURCE_SETTINGS_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107308"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107346"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ACCOUNT_TYPE_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107309"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107347"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ALTERNATE_PARENT_COLUMN
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107310"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107348"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ALTERNATE_SAVED_SEARCH
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107311"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107349"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CATEGORY_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107312"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107350"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATA_SOURCE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107313"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107351"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATA_STORAGE_FOR_PARENT_RECOR
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107314"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107352"
              stepCounter: "4295"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107315"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107353"
              stepCounter: "4295"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DO_NOT_USE_STANDARD_SAVED_SEA
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107316"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107354"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DUMMY_PARENT_ALIAS_AFFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107317"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107355"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DUMMY_PARENT_CHILD_AFFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107318"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107356"
              stepCounter: "4295"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: EXCLUDE_ALTERNATE_PARENT_COLU
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107319"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107357"
              stepCounter: "4295"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: EXCLUDE_UPPER_LEVEL_MEMBERS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107320"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107358"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FILTER_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107321"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107359"
              stepCounter: "4295"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107322"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107360"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ITEM_TYPE_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107323"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107361"
              stepCounter: "4295"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107324"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107362"
              stepCounter: "4295"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NSPB___DATA_SOURCE_SETTINGS_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107325"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107363"
              stepCounter: "4295"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107326"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107364"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SORT_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107327"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107365"
              stepCounter: "4295"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TOP_LEVEL_PARENT_VALUE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107328"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107366"
              stepCounter: "4295"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: USE_DYNAMIC_CALC
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107329"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107367"
              stepCounter: "4295"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107330"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107368"
              stepCounter: "4295"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107331"
                    stepCounter: "4293"
                transform: ""
          - columnReference:
              columnCounter: "107369"
              stepCounter: "4295"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "107332"
                    stepCounter: "4293"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107370"
              stepCounter: "4295"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107371"
              stepCounter: "4295"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "107395"
              stepCounter: "4295"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107372"
              stepCounter: "4295"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107373"
              stepCounter: "4295"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107374"
              stepCounter: "4295"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107375"
              stepCounter: "4295"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: NSPB___DATA_SOURCE_SETTINGS
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___DATA_SOURCE_SETTINGS') }} "NSPB___DATA_SOURCE_SETTINGS"
            name: PSTG_NSPB___DATA_SOURCE_SETTINGS
            noLinkRefs: []
      name: PSTG_NSPB___DATA_SOURCE_SETTINGS
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4295"
