steps:
  PSTG_NSPB___SAVED_SEARCH_SETTINGS-4241:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105426"
              stepCounter: "4241"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_NSPB___SAVED_SEARCH_SETTINGS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "105427"
              stepCounter: "4241"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: NSPB___SAVED_SEARCH_SETTING_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45448"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105428"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ACCOUNT_TYPE_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45449"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105429"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ALTERNATE_PARENT_COLUMN
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45450"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105430"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ALTERNATE_SAVED_SEARCH
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45451"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105431"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CATEGORY_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45452"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105432"
              stepCounter: "4241"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45453"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105433"
              stepCounter: "4241"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DO_NOT_USE_STANDARD_SAVED_SEA
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45454"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105434"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DUMMY_PARENT_ALIAS_AFFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45455"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105435"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DUMMY_PARENT_CHILD_AFFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45456"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105436"
              stepCounter: "4241"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: EXCLUDE_UPPER_LEVEL_MEMBERS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45457"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105437"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FILTER_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45458"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105438"
              stepCounter: "4241"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45459"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105439"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ITEM_TYPE_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45460"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105440"
              stepCounter: "4241"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45461"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105441"
              stepCounter: "4241"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NSPB___SAVED_SEARCH_SETTING_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45462"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105442"
              stepCounter: "4241"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45463"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105443"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SAVED_SEARCH_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45464"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105444"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SORT_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45465"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105445"
              stepCounter: "4241"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TOP_LEVEL_PARENT_VALUE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45466"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105446"
              stepCounter: "4241"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: USE_DYNAMIC_CALC
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45467"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105447"
              stepCounter: "4241"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45468"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105448"
              stepCounter: "4241"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45469"
                    stepCounter: "2776"
                transform: ""
          - columnReference:
              columnCounter: "105449"
              stepCounter: "4241"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45470"
                    stepCounter: "2776"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105450"
              stepCounter: "4241"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105451"
              stepCounter: "4241"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "107148"
              stepCounter: "4241"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105452"
              stepCounter: "4241"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105453"
              stepCounter: "4241"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105454"
              stepCounter: "4241"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105455"
              stepCounter: "4241"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: NSPB___SAVED_SEARCH_SETTINGS
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___SAVED_SEARCH_SETTINGS') }} "NSPB___SAVED_SEARCH_SETTINGS"
            name: PSTG_NSPB___SAVED_SEARCH_SETTINGS
            noLinkRefs: []
      name: PSTG_NSPB___SAVED_SEARCH_SETTINGS
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4241"
