steps:
  PSTG_STC_CONFIG_FIELDS-3998:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98186"
              stepCounter: "3998"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_STC_CONFIG_FIELDS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "98187"
              stepCounter: "3998"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48374"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98188"
              stepCounter: "3998"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DEFAULT_VALUE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48375"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98189"
              stepCounter: "3998"
            dataType: VARCHAR(262136)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DESCRIPTION
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48376"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98190"
              stepCounter: "3998"
            dataType: VARCHAR(262136)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: HELP_TEXT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48377"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98191"
              stepCounter: "3998"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ID_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48378"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98192"
              stepCounter: "3998"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48379"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98193"
              stepCounter: "3998"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48380"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98194"
              stepCounter: "3998"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48381"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98195"
              stepCounter: "3998"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: STC_CONFIG_FIELDS_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48382"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98196"
              stepCounter: "3998"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: STC_CONFIG_FIELDS_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48383"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98197"
              stepCounter: "3998"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: STC_CONFIG_FIELDS_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48384"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98198"
              stepCounter: "3998"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TYPE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48385"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98199"
              stepCounter: "3998"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48386"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98200"
              stepCounter: "3998"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48387"
                    stepCounter: "2911"
                transform: ""
          - columnReference:
              columnCounter: "98201"
              stepCounter: "3998"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48388"
                    stepCounter: "2911"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98202"
              stepCounter: "3998"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98203"
              stepCounter: "3998"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "98951"
              stepCounter: "3998"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98204"
              stepCounter: "3998"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98205"
              stepCounter: "3998"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98206"
              stepCounter: "3998"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98207"
              stepCounter: "3998"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: STC_CONFIG_FIELDS
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'STC_CONFIG_FIELDS') }} "STC_CONFIG_FIELDS"
            name: PSTG_STC_CONFIG_FIELDS
            noLinkRefs: []
      name: PSTG_STC_CONFIG_FIELDS
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3998"
