steps:
  PSTG_VAT_ONLINE_CONFIGURATION-3647:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87649"
              stepCounter: "3647"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_VAT_ONLINE_CONFIGURATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "87650"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: COUNTRY_CODE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50247"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87651"
              stepCounter: "3647"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50248"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87652"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: HELP_TEXT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50249"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87653"
              stepCounter: "3647"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ISMANDATORY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50250"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87654"
              stepCounter: "3647"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ISVISIBLE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50251"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87655"
              stepCounter: "3647"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50252"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87656"
              stepCounter: "3647"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_NEW_TAX_FILING
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50253"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87657"
              stepCounter: "3647"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_NONDEDUCTIBLE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50254"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87658"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LABEL
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50255"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87659"
              stepCounter: "3647"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50256"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87660"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50257"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87661"
              stepCounter: "3647"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50258"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87662"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PRODUCT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50259"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87663"
              stepCounter: "3647"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SUBSIDIARY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50260"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87664"
              stepCounter: "3647"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAB_ORDER
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50261"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87665"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TYPE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50262"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87666"
              stepCounter: "3647"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: VALUE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50263"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87667"
              stepCounter: "3647"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: VAT_ONLINE_CONFIGURATION_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50264"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87668"
              stepCounter: "3647"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: VAT_ONLINE_CONFIGURATION_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50265"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87669"
              stepCounter: "3647"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50266"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87670"
              stepCounter: "3647"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50267"
                    stepCounter: "3000"
                transform: ""
          - columnReference:
              columnCounter: "87671"
              stepCounter: "3647"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "50268"
                    stepCounter: "3000"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87672"
              stepCounter: "3647"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87673"
              stepCounter: "3647"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "88273"
              stepCounter: "3647"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87674"
              stepCounter: "3647"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87675"
              stepCounter: "3647"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87676"
              stepCounter: "3647"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "87677"
              stepCounter: "3647"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: VAT_ONLINE_CONFIGURATION
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'VAT_ONLINE_CONFIGURATION') }} "VAT_ONLINE_CONFIGURATION"
            name: PSTG_VAT_ONLINE_CONFIGURATION
            noLinkRefs: []
      name: PSTG_VAT_ONLINE_CONFIGURATION
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3647"
