steps:
  PSTG_DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C-4709:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_SALESFORCE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116310"
              stepCounter: "4709"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "116311"
              stepCounter: "4709"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109259"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116312"
              stepCounter: "4709"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109260"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116313"
              stepCounter: "4709"
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109261"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116314"
              stepCounter: "4709"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109262"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116315"
              stepCounter: "4709"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109263"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116316"
              stepCounter: "4709"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109264"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116317"
              stepCounter: "4709"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_BY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109265"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116318"
              stepCounter: "4709"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SYSTEM_MODSTAMP
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109266"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116319"
              stepCounter: "4709"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_ENVELOPE_CONFIGURATION_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109267"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116320"
              stepCounter: "4709"
            dataType: VARCHAR(60)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_EXTENSION_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109268"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116321"
              stepCounter: "4709"
            dataType: VARCHAR(6000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_FILTER_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109269"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116322"
              stepCounter: "4709"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_NAME_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109270"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116323"
              stepCounter: "4709"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_READ_ONLY_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109271"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116324"
              stepCounter: "4709"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_REQUIRED_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109272"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116325"
              stepCounter: "4709"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_SEQUENCE_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109273"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116326"
              stepCounter: "4709"
            dataType: VARCHAR(120)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_SOURCE_ID_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109274"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116327"
              stepCounter: "4709"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_TYPE_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109275"
                    stepCounter: "4386"
                transform: ""
          - columnReference:
              columnCounter: "116328"
              stepCounter: "4709"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109276"
                    stepCounter: "4386"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116329"
              stepCounter: "4709"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116330"
              stepCounter: "4709"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "117843"
              stepCounter: "4709"
            config: {}
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'SALESFORCE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116331"
              stepCounter: "4709"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116332"
              stepCounter: "4709"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116333"
              stepCounter: "4709"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116334"
              stepCounter: "4709"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_SALESFORCE
                nodeName: DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C
            join:
              joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C') }} "DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C"
            name: PSTG_DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C
            noLinkRefs: []
      name: PSTG_DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4709"
