steps:
  PSTG_STC_NEXUS_CONFIGURATION-4000:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98227"
              stepCounter: "4000"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_STC_NEXUS_CONFIGURATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "98228"
              stepCounter: "4000"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREDIT_MEMO
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48401"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98229"
              stepCounter: "4000"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48402"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98230"
              stepCounter: "4000"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48403"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98231"
              stepCounter: "4000"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48404"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98232"
              stepCounter: "4000"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NEXUS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48405"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98233"
              stepCounter: "4000"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48406"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98234"
              stepCounter: "4000"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PURCHASE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48407"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98235"
              stepCounter: "4000"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SALES
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48408"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98236"
              stepCounter: "4000"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: STC_NEXUS_CONFIGURATION_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48409"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98237"
              stepCounter: "4000"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: STC_NEXUS_CONFIGURATION_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48410"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98238"
              stepCounter: "4000"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48411"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98239"
              stepCounter: "4000"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48412"
                    stepCounter: "2913"
                transform: ""
          - columnReference:
              columnCounter: "98240"
              stepCounter: "4000"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48413"
                    stepCounter: "2913"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98241"
              stepCounter: "4000"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98242"
              stepCounter: "4000"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "98949"
              stepCounter: "4000"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98243"
              stepCounter: "4000"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98244"
              stepCounter: "4000"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98245"
              stepCounter: "4000"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98246"
              stepCounter: "4000"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: STC_NEXUS_CONFIGURATION
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'STC_NEXUS_CONFIGURATION') }} "STC_NEXUS_CONFIGURATION"
            name: PSTG_STC_NEXUS_CONFIGURATION
            noLinkRefs: []
      name: PSTG_STC_NEXUS_CONFIGURATION
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4000"
