steps:
  PSTG_FISCAL_YEAR_SETTINGS-4763:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_SALESFORCE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118011"
              stepCounter: "4763"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_FISCAL_YEAR_SETTINGS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "118012"
              stepCounter: "4763"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110283"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118013"
              stepCounter: "4763"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PERIOD_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110284"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118014"
              stepCounter: "4763"
            dataType: DATE
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110285"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118015"
              stepCounter: "4763"
            dataType: DATE
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110286"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118016"
              stepCounter: "4763"
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110287"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118017"
              stepCounter: "4763"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_STANDARD_YEAR
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110288"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118018"
              stepCounter: "4763"
            dataType: VARCHAR(120)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: YEAR_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110289"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118019"
              stepCounter: "4763"
            dataType: VARCHAR(120)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: QUARTER_LABEL_SCHEME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110290"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118020"
              stepCounter: "4763"
            dataType: VARCHAR(120)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PERIOD_LABEL_SCHEME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110291"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118021"
              stepCounter: "4763"
            dataType: VARCHAR(120)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: WEEK_LABEL_SCHEME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110292"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118022"
              stepCounter: "4763"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: QUARTER_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110293"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118023"
              stepCounter: "4763"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PERIOD_PREFIX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110294"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118024"
              stepCounter: "4763"
            dataType: NUMBER(38,0)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: WEEK_START_DAY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110295"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118025"
              stepCounter: "4763"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DESCRIPTION
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110296"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118026"
              stepCounter: "4763"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SYSTEM_MODSTAMP
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110297"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118027"
              stepCounter: "4763"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110298"
                    stepCounter: "4438"
                transform: ""
          - columnReference:
              columnCounter: "118028"
              stepCounter: "4763"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "110299"
                    stepCounter: "4438"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118029"
              stepCounter: "4763"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118030"
              stepCounter: "4763"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "118656"
              stepCounter: "4763"
            config: {}
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'SALESFORCE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118031"
              stepCounter: "4763"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118032"
              stepCounter: "4763"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118033"
              stepCounter: "4763"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "118034"
              stepCounter: "4763"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_SALESFORCE
                nodeName: FISCAL_YEAR_SETTINGS
            join:
              joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'FISCAL_YEAR_SETTINGS') }} "FISCAL_YEAR_SETTINGS"
            name: PSTG_FISCAL_YEAR_SETTINGS
            noLinkRefs: []
      name: PSTG_FISCAL_YEAR_SETTINGS
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4763"
