steps:
  PSTG_TAX_AUDIT_FILES_CONFIGURATION-3598:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86207"
              stepCounter: "3598"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_TAX_AUDIT_FILES_CONFIGURATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "86208"
              stepCounter: "3598"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: TAX_AUDIT_FILES_CONFIGURATI_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49148"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86209"
              stepCounter: "3598"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49149"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86210"
              stepCounter: "3598"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49150"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86211"
              stepCounter: "3598"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: KEY_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49151"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86212"
              stepCounter: "3598"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49152"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86213"
              stepCounter: "3598"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49153"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86214"
              stepCounter: "3598"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REPORT_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49154"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86215"
              stepCounter: "3598"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SUBSIDIARY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49155"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86216"
              stepCounter: "3598"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAX_AUDIT_FILES_CONFIGURATI_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49156"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86217"
              stepCounter: "3598"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: VALUE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49157"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86218"
              stepCounter: "3598"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49158"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86219"
              stepCounter: "3598"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49159"
                    stepCounter: "2951"
                transform: ""
          - columnReference:
              columnCounter: "86220"
              stepCounter: "3598"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49160"
                    stepCounter: "2951"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86221"
              stepCounter: "3598"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86222"
              stepCounter: "3598"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "88324"
              stepCounter: "3598"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86223"
              stepCounter: "3598"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86224"
              stepCounter: "3598"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86225"
              stepCounter: "3598"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86226"
              stepCounter: "3598"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: TAX_AUDIT_FILES_CONFIGURATION
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'TAX_AUDIT_FILES_CONFIGURATION') }} "TAX_AUDIT_FILES_CONFIGURATION"
            name: PSTG_TAX_AUDIT_FILES_CONFIGURATION
            noLinkRefs: []
      name: PSTG_TAX_AUDIT_FILES_CONFIGURATION
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3598"
