steps:
  PSTG_SII_LIST_VALUES-3989:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98034"
              stepCounter: "3989"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_SII_LIST_VALUES_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "98035"
              stepCounter: "3989"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: SII_LIST_VALUES_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48285"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98036"
              stepCounter: "3989"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CODE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48286"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98037"
              stepCounter: "3989"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48287"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98038"
              stepCounter: "3989"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48288"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98039"
              stepCounter: "3989"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48289"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98040"
              stepCounter: "3989"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LIST_TYPE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48290"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98041"
              stepCounter: "3989"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48291"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98042"
              stepCounter: "3989"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SII_LIST_VALUES_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48292"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98043"
              stepCounter: "3989"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SII_LIST_VALUES_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48293"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98044"
              stepCounter: "3989"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48294"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98045"
              stepCounter: "3989"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48295"
                    stepCounter: "2902"
                transform: ""
          - columnReference:
              columnCounter: "98046"
              stepCounter: "3989"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48296"
                    stepCounter: "2902"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98047"
              stepCounter: "3989"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98048"
              stepCounter: "3989"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "98960"
              stepCounter: "3989"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98049"
              stepCounter: "3989"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98050"
              stepCounter: "3989"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98051"
              stepCounter: "3989"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98052"
              stepCounter: "3989"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: SII_LIST_VALUES
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'SII_LIST_VALUES') }} "SII_LIST_VALUES"
            name: PSTG_SII_LIST_VALUES
            noLinkRefs: []
      name: PSTG_SII_LIST_VALUES
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3989"
