steps:
  PSTG_DFSLE_AGREEMENT_CONFIGURATION_HISTORY-4698:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_SALESFORCE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116019"
              stepCounter: "4698"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_DFSLE_AGREEMENT_CONFIGURATION_HISTORY_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "116020"
              stepCounter: "4698"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109045"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116021"
              stepCounter: "4698"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109046"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116022"
              stepCounter: "4698"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109047"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116023"
              stepCounter: "4698"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109048"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116024"
              stepCounter: "4698"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109049"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116025"
              stepCounter: "4698"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FIELD
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109050"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116026"
              stepCounter: "4698"
            dataType: VARCHAR(120)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATA_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109051"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116027"
              stepCounter: "4698"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: OLD_VALUE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109052"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116028"
              stepCounter: "4698"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NEW_VALUE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109053"
                    stepCounter: "4375"
                transform: ""
          - columnReference:
              columnCounter: "116029"
              stepCounter: "4698"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109054"
                    stepCounter: "4375"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116030"
              stepCounter: "4698"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116031"
              stepCounter: "4698"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "117855"
              stepCounter: "4698"
            config: {}
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'SALESFORCE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116032"
              stepCounter: "4698"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116033"
              stepCounter: "4698"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116034"
              stepCounter: "4698"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116035"
              stepCounter: "4698"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_SALESFORCE
                nodeName: DFSLE_AGREEMENT_CONFIGURATION_HISTORY
            join:
              joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_AGREEMENT_CONFIGURATION_HISTORY') }} "DFSLE_AGREEMENT_CONFIGURATION_HISTORY"
            name: PSTG_DFSLE_AGREEMENT_CONFIGURATION_HISTORY
            noLinkRefs: []
      name: PSTG_DFSLE_AGREEMENT_CONFIGURATION_HISTORY
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4698"
