steps:
  PSTG_EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP-3401:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81214"
              stepCounter: "3401"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "81215"
              stepCounter: "3401"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: EP_DUMMY_LIST_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41720"
                    stepCounter: "2560"
                transform: ""
          - columnReference:
              columnCounter: "81216"
              stepCounter: "3401"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: EP_QUEUE_SETTINGS_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41721"
                    stepCounter: "2560"
                transform: ""
          - columnReference:
              columnCounter: "81217"
              stepCounter: "3401"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41722"
                    stepCounter: "2560"
                transform: ""
          - columnReference:
              columnCounter: "81218"
              stepCounter: "3401"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41723"
                    stepCounter: "2560"
                transform: ""
          - columnReference:
              columnCounter: "81219"
              stepCounter: "3401"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41724"
                    stepCounter: "2560"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81220"
              stepCounter: "3401"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81221"
              stepCounter: "3401"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "85751"
              stepCounter: "3401"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81222"
              stepCounter: "3401"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81223"
              stepCounter: "3401"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81224"
              stepCounter: "3401"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "81225"
              stepCounter: "3401"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP') }} "EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP"
            name: PSTG_EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP
            noLinkRefs: []
      name: PSTG_EP_QUEUE_SETTINGS_DUMMY_PAYMENT_CREATOR_MAP
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3401"
