steps:
  PSTG_ONLINE_FILING_CONFIGURATION-4247:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105564"
              stepCounter: "4247"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_ONLINE_FILING_CONFIGURATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "105565"
              stepCounter: "4247"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: ONLINE_FILING_CONFIGURATION_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45544"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105566"
              stepCounter: "4247"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CONFIGURATION
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45545"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105567"
              stepCounter: "4247"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45546"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105568"
              stepCounter: "4247"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_FOR_TEST
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45547"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105569"
              stepCounter: "4247"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45548"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105570"
              stepCounter: "4247"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45549"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105571"
              stepCounter: "4247"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NEXUS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45550"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105572"
              stepCounter: "4247"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ONLINE_FILING_CONFIGURATION_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45551"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105573"
              stepCounter: "4247"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ONLINE_FILING_CONFIGURATION_NA
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45552"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105574"
              stepCounter: "4247"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45553"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105575"
              stepCounter: "4247"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PROCESS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45554"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105576"
              stepCounter: "4247"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45555"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105577"
              stepCounter: "4247"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45556"
                    stepCounter: "2782"
                transform: ""
          - columnReference:
              columnCounter: "105578"
              stepCounter: "4247"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45557"
                    stepCounter: "2782"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105579"
              stepCounter: "4247"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105580"
              stepCounter: "4247"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "107047"
              stepCounter: "4247"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105581"
              stepCounter: "4247"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105582"
              stepCounter: "4247"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105583"
              stepCounter: "4247"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105584"
              stepCounter: "4247"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: ONLINE_FILING_CONFIGURATION
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'ONLINE_FILING_CONFIGURATION') }} "ONLINE_FILING_CONFIGURATION"
            name: PSTG_ONLINE_FILING_CONFIGURATION
            noLinkRefs: []
      name: PSTG_ONLINE_FILING_CONFIGURATION
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4247"
