steps:
  PSTG_TAF_REPORT_THRESHOLD_CONFIGUR-3593:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86106"
              stepCounter: "3593"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_TAF_REPORT_THRESHOLD_CONFIGUR_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "86107"
              stepCounter: "3593"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49082"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86108"
              stepCounter: "3593"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: GOVERNANCE_LIMIT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49083"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86109"
              stepCounter: "3593"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49084"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86110"
              stepCounter: "3593"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49085"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86111"
              stepCounter: "3593"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49086"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86112"
              stepCounter: "3593"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: RUNTIME_LIMIT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49087"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86113"
              stepCounter: "3593"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SEARCH_RESULTS_LIMIT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49088"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86114"
              stepCounter: "3593"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAF_REPORT_THRESHOLD_CONFIG_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49089"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86115"
              stepCounter: "3593"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: TAF_REPORT_THRESHOLD_CONFIG_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49090"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86116"
              stepCounter: "3593"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAF_REPORT_THRESHOLD_CONFIG_NA
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49091"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86117"
              stepCounter: "3593"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49092"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86118"
              stepCounter: "3593"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49093"
                    stepCounter: "2946"
                transform: ""
          - columnReference:
              columnCounter: "86119"
              stepCounter: "3593"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49094"
                    stepCounter: "2946"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86120"
              stepCounter: "3593"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86121"
              stepCounter: "3593"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "88329"
              stepCounter: "3593"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86122"
              stepCounter: "3593"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86123"
              stepCounter: "3593"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86124"
              stepCounter: "3593"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86125"
              stepCounter: "3593"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: TAF_REPORT_THRESHOLD_CONFIGUR
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'TAF_REPORT_THRESHOLD_CONFIGUR') }} "TAF_REPORT_THRESHOLD_CONFIGUR"
            name: PSTG_TAF_REPORT_THRESHOLD_CONFIGUR
            noLinkRefs: []
      name: PSTG_TAF_REPORT_THRESHOLD_CONFIGUR
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3593"
