steps:
  PSTG_NSPB___CONFIG-4234:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105242"
              stepCounter: "4234"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_NSPB___CONFIG_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "105243"
              stepCounter: "4234"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: NSPB___CONFIG_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45313"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105244"
              stepCounter: "4234"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45314"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105245"
              stepCounter: "4234"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45315"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105246"
              stepCounter: "4234"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: KEY_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45316"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105247"
              stepCounter: "4234"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45317"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105248"
              stepCounter: "4234"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NSPB___CONFIG_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45318"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105249"
              stepCounter: "4234"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45319"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105250"
              stepCounter: "4234"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: VALUE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45320"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105251"
              stepCounter: "4234"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45321"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105252"
              stepCounter: "4234"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45322"
                    stepCounter: "2769"
                transform: ""
          - columnReference:
              columnCounter: "105253"
              stepCounter: "4234"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "45323"
                    stepCounter: "2769"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105254"
              stepCounter: "4234"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105255"
              stepCounter: "4234"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "107155"
              stepCounter: "4234"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105256"
              stepCounter: "4234"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105257"
              stepCounter: "4234"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105258"
              stepCounter: "4234"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "105259"
              stepCounter: "4234"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: NSPB___CONFIG
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___CONFIG') }} "NSPB___CONFIG"
            name: PSTG_NSPB___CONFIG
            noLinkRefs: []
      name: PSTG_NSPB___CONFIG
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4234"
