steps:
  PSTG_ED_CONFIGURABLE_FIELD_LIST-3369:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80351"
              stepCounter: "3369"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_ED_CONFIGURABLE_FIELD_LIST_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "80352"
              stepCounter: "3369"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: LIST_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41081"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80353"
              stepCounter: "3369"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41082"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80354"
              stepCounter: "3369"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ED_CONFIGURABLE_FIELD_LIST_EXT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41083"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80355"
              stepCounter: "3369"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_RECORD_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41084"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80356"
              stepCounter: "3369"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41085"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80357"
              stepCounter: "3369"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LIST_ITEM_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41086"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80358"
              stepCounter: "3369"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41087"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80359"
              stepCounter: "3369"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41088"
                    stepCounter: "2528"
                transform: ""
          - columnReference:
              columnCounter: "80360"
              stepCounter: "3369"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "41089"
                    stepCounter: "2528"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80361"
              stepCounter: "3369"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80362"
              stepCounter: "3369"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "83730"
              stepCounter: "3369"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80363"
              stepCounter: "3369"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80364"
              stepCounter: "3369"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80365"
              stepCounter: "3369"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "80366"
              stepCounter: "3369"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: ED_CONFIGURABLE_FIELD_LIST
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'ED_CONFIGURABLE_FIELD_LIST') }} "ED_CONFIGURABLE_FIELD_LIST"
            name: PSTG_ED_CONFIGURABLE_FIELD_LIST
            noLinkRefs: []
      name: PSTG_ED_CONFIGURABLE_FIELD_LIST
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3369"
