steps:
  PSTG_DFSLE_AGREEMENT_CONFIGURATION_C-4697:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_SALESFORCE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "115998"
              stepCounter: "4697"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_DFSLE_AGREEMENT_CONFIGURATION_C_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "115999"
              stepCounter: "4697"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109031"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116000"
              stepCounter: "4697"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: OWNER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109032"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116001"
              stepCounter: "4697"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109033"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116002"
              stepCounter: "4697"
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109034"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116003"
              stepCounter: "4697"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109035"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116004"
              stepCounter: "4697"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109036"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116005"
              stepCounter: "4697"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109037"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116006"
              stepCounter: "4697"
            dataType: VARCHAR(18)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_BY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109038"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116007"
              stepCounter: "4697"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SYSTEM_MODSTAMP
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109039"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116008"
              stepCounter: "4697"
            dataType: DATE
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_ACTIVITY_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109040"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116009"
              stepCounter: "4697"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_FOLDER_ID_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109041"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116010"
              stepCounter: "4697"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_SOURCE_OBJECT_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109042"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116011"
              stepCounter: "4697"
            dataType: VARCHAR(765)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DFSLE_TEMP_FOLDER_ID_C
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109043"
                    stepCounter: "4374"
                transform: ""
          - columnReference:
              columnCounter: "116012"
              stepCounter: "4697"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "109044"
                    stepCounter: "4374"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116013"
              stepCounter: "4697"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116014"
              stepCounter: "4697"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "117856"
              stepCounter: "4697"
            config: {}
            dataType: VARCHAR(240)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'SALESFORCE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116015"
              stepCounter: "4697"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116016"
              stepCounter: "4697"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116017"
              stepCounter: "4697"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "116018"
              stepCounter: "4697"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_SALESFORCE
                nodeName: DFSLE_AGREEMENT_CONFIGURATION_C
            join:
              joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_AGREEMENT_CONFIGURATION_C') }} "DFSLE_AGREEMENT_CONFIGURATION_C"
            name: PSTG_DFSLE_AGREEMENT_CONFIGURATION_C
            noLinkRefs: []
      name: PSTG_DFSLE_AGREEMENT_CONFIGURATION_C
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4697"
