steps:
  PSTG_SUBNAV__SETTINGS-4002:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98266"
              stepCounter: "4002"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_SUBNAV__SETTINGS_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "98267"
              stepCounter: "4002"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48426"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98268"
              stepCounter: "4002"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48427"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98269"
              stepCounter: "4002"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48428"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98270"
              stepCounter: "4002"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48429"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98271"
              stepCounter: "4002"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ROLE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48430"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98272"
              stepCounter: "4002"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SUBNAV__SETTINGS_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48431"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98273"
              stepCounter: "4002"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: SUBNAV__SETTINGS_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48432"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98274"
              stepCounter: "4002"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SUBNAV__SETTINGS_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48433"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98275"
              stepCounter: "4002"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TYPE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48434"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98276"
              stepCounter: "4002"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: USER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48435"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98277"
              stepCounter: "4002"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: VALUE_0
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48436"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98278"
              stepCounter: "4002"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48437"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98279"
              stepCounter: "4002"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48438"
                    stepCounter: "2915"
                transform: ""
          - columnReference:
              columnCounter: "98280"
              stepCounter: "4002"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "48439"
                    stepCounter: "2915"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98281"
              stepCounter: "4002"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98282"
              stepCounter: "4002"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "98947"
              stepCounter: "4002"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98283"
              stepCounter: "4002"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98284"
              stepCounter: "4002"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98285"
              stepCounter: "4002"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "98286"
              stepCounter: "4002"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: SUBNAV__SETTINGS
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'SUBNAV__SETTINGS') }} "SUBNAV__SETTINGS"
            name: PSTG_SUBNAV__SETTINGS
            noLinkRefs: []
      name: PSTG_SUBNAV__SETTINGS
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "4002"
