steps:
  PSTG_GOBD_TAF_REPORT_CONFIG-3495:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83605"
              stepCounter: "3495"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_GOBD_TAF_REPORT_CONFIG_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "83606"
              stepCounter: "3495"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43453"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83607"
              stepCounter: "3495"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: GOBD_TAF_REPORT_CONFIG_EXTID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43454"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83608"
              stepCounter: "3495"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: GOBD_TAF_REPORT_CONFIG_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43455"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83609"
              stepCounter: "3495"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: GOBD_TAF_REPORT_CONFIG_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43456"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83610"
              stepCounter: "3495"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43457"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83611"
              stepCounter: "3495"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43458"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83612"
              stepCounter: "3495"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43459"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83613"
              stepCounter: "3495"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SUBSIDIARY_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43460"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83614"
              stepCounter: "3495"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: USE_NEW_ENGINE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43461"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83615"
              stepCounter: "3495"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43462"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83616"
              stepCounter: "3495"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43463"
                    stepCounter: "2654"
                transform: ""
          - columnReference:
              columnCounter: "83617"
              stepCounter: "3495"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "43464"
                    stepCounter: "2654"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83618"
              stepCounter: "3495"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83619"
              stepCounter: "3495"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "85842"
              stepCounter: "3495"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83620"
              stepCounter: "3495"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83621"
              stepCounter: "3495"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83622"
              stepCounter: "3495"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "83623"
              stepCounter: "3495"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: GOBD_TAF_REPORT_CONFIG
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'GOBD_TAF_REPORT_CONFIG') }} "GOBD_TAF_REPORT_CONFIG"
            name: PSTG_GOBD_TAF_REPORT_CONFIG
            noLinkRefs: []
      name: PSTG_GOBD_TAF_REPORT_CONFIG
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3495"
