steps:
  PSTG_TAF_SETUP_CONFIGURATION_FIELD-3594:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_NETSUITE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86126"
              stepCounter: "3594"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_TAF_SETUP_CONFIGURATION_FIELD_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "86127"
              stepCounter: "3594"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: TAF_SETUP_CONFIGURATION_FIE_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49095"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86128"
              stepCounter: "3594"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_CREATED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49096"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86129"
              stepCounter: "3594"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FIELD_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49097"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86130"
              stepCounter: "3594"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FIELD_TYPE_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49098"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86131"
              stepCounter: "3594"
            dataType: VARCHAR(4)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_INACTIVE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49099"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86132"
              stepCounter: "3594"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_MODIFIED_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49100"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86133"
              stepCounter: "3594"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: PARENT_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49101"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86134"
              stepCounter: "3594"
            dataType: VARCHAR(16000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REPORT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49102"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86135"
              stepCounter: "3594"
            dataType: VARCHAR(1020)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAF_SETUP_CONFIGURATION_FIE_EX
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49103"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86136"
              stepCounter: "3594"
            dataType: VARCHAR(3996)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: TAF_SETUP_CONFIGURATION_FIE_NA
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49104"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86137"
              stepCounter: "3594"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49105"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86138"
              stepCounter: "3594"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DATE_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49106"
                    stepCounter: "2947"
                transform: ""
          - columnReference:
              columnCounter: "86139"
              stepCounter: "3594"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "49107"
                    stepCounter: "2947"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86140"
              stepCounter: "3594"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86141"
              stepCounter: "3594"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - appliedColumnTests: {}
            columnReference:
              columnCounter: "88328"
              stepCounter: "3594"
            config: {}
            dataType: VARCHAR(256)
            description: ""
            hashDetails: null
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'NETSUITE'"
            systemColumnType: None
            type: Column
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86142"
              stepCounter: "3594"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86143"
              stepCounter: "3594"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86144"
              stepCounter: "3594"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "86145"
              stepCounter: "3594"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_NETSUITE
                nodeName: TAF_SETUP_CONFIGURATION_FIELD
            join:
              joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'TAF_SETUP_CONFIGURATION_FIELD') }} "TAF_SETUP_CONFIGURATION_FIELD"
            name: PSTG_TAF_SETUP_CONFIGURATION_FIELD
            noLinkRefs: []
      name: PSTG_TAF_SETUP_CONFIGURATION_FIELD
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "3594"
