steps:
  PSTG_ERP_COMPLIANCE_ROUTES-5408:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_ORACLE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185375"
              stepCounter: "5408"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_ERP_COMPLIANCE_ROUTES_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "185376"
              stepCounter: "5408"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183461"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185377"
              stepCounter: "5408"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: COMPLIANCE_ROUTE_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183462"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185378"
              stepCounter: "5408"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183463"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185379"
              stepCounter: "5408"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REQUIRED_LICENSE_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183464"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185380"
              stepCounter: "5408"
            dataType: VARCHAR(1000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DESCRIPTION
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183465"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185381"
              stepCounter: "5408"
            dataType: VARCHAR(80)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FAMILIAR_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183466"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185382"
              stepCounter: "5408"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REQUIRES_CONSUMER_PERMIT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183467"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185383"
              stepCounter: "5408"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REQUIRES_LICENSE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183468"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185384"
              stepCounter: "5408"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REQUIRES_CUSTOMER_PERMIT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183469"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185385"
              stepCounter: "5408"
            dataType: VARCHAR(7)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DISPLAY_COLOR
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183470"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185386"
              stepCounter: "5408"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183471"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185387"
              stepCounter: "5408"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183472"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185388"
              stepCounter: "5408"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATION_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183473"
                    stepCounter: "5291"
                transform: ""
          - columnReference:
              columnCounter: "185389"
              stepCounter: "5408"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183474"
                    stepCounter: "5291"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185390"
              stepCounter: "5408"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185391"
              stepCounter: "5408"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185392"
              stepCounter: "5408"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185393"
              stepCounter: "5408"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185394"
              stepCounter: "5408"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185395"
              stepCounter: "5408"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185396"
              stepCounter: "5408"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "0"
                    stepCounter: "0"
                transform: "'ORACLE XWS'"
            systemColumnType: None
            transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_ORACLE_XWS
                nodeName: ERP_COMPLIANCE_ROUTES
            join:
              joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'ERP_COMPLIANCE_ROUTES') }} "ERP_COMPLIANCE_ROUTES"
            name: PSTG_ERP_COMPLIANCE_ROUTES
            noLinkRefs: []
      name: PSTG_ERP_COMPLIANCE_ROUTES
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "5408"
