steps:
  PSTG_ERP_FULFILLMENT_ROUTES-5430:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: PERSISTENT_STAGING_ORACLE
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185803"
              stepCounter: "5430"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSurrogateKey: true
            name: PSTG_ERP_FULFILLMENT_ROUTES_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: "185804"
              stepCounter: "5430"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isBusinessKey: true
            name: FULFILLMENT_ROUTE_ID
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183680"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185805"
              stepCounter: "5430"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183681"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185806"
              stepCounter: "5430"
            dataType: VARCHAR(30)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: REGION_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183682"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185807"
              stepCounter: "5430"
            dataType: VARCHAR(30)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: ROUTE_TO_WMS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183683"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185808"
              stepCounter: "5430"
            dataType: FLOAT
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATED_BY
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183684"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185809"
              stepCounter: "5430"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: CREATION_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183685"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185810"
              stepCounter: "5430"
            dataType: TIMESTAMP_NTZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: LAST_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183686"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185811"
              stepCounter: "5430"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_UPGRADEABLE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183687"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185812"
              stepCounter: "5430"
            dataType: VARCHAR(30)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: BILL_TO_VENDOR_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183688"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185813"
              stepCounter: "5430"
            dataType: VARCHAR(1)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: IS_LINE_HAUL
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183689"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185814"
              stepCounter: "5430"
            dataType: VARCHAR(1000)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: DESCRIPTION
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183690"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185815"
              stepCounter: "5430"
            dataType: VARCHAR(30)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: SHIP_FROM_VENDOR_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183691"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185816"
              stepCounter: "5430"
            dataType: VARCHAR(80)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: FAMILIAR_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183692"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185817"
              stepCounter: "5430"
            dataType: BOOLEAN
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_DELETED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183693"
                    stepCounter: "5307"
                transform: ""
          - columnReference:
              columnCounter: "185818"
              stepCounter: "5430"
            dataType: TIMESTAMP_TZ(9)
            description: ""
            hashDetails: null
            isChangeTracking: true
            name: _FIVETRAN_SYNCED
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "183694"
                    stepCounter: "5307"
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185819"
              stepCounter: "5430"
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185820"
              stepCounter: "5430"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185821"
              stepCounter: "5430"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185822"
              stepCounter: "5430"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185823"
              stepCounter: "5430"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185824"
              stepCounter: "5430"
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "185825"
              stepCounter: "5430"
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            keyColumnType: None
            name: SOURCE_SYSTEM
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: "0"
                    stepCounter: "0"
                transform: "'ORACLE XWS'"
            systemColumnType: None
            transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SOURCES_ORACLE_XWS
                nodeName: ERP_FULFILLMENT_ROUTES
            join:
              joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'ERP_FULFILLMENT_ROUTES') }} "ERP_FULFILLMENT_ROUTES"
            name: PSTG_ERP_FULFILLMENT_ROUTES
            noLinkRefs: []
      name: PSTG_ERP_FULFILLMENT_ROUTES
      overrideSQL: false
      schema: ""
      sqlType: "18"
      type: sql
    stepCounter: "5430"
