steps:
  TAF_REPORT_THRESHOLD_CONFIGUR-2946:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49082"
              stepCounter: "2946"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49083"
              stepCounter: "2946"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: GOVERNANCE_LIMIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49084"
              stepCounter: "2946"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49085"
              stepCounter: "2946"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49086"
              stepCounter: "2946"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49087"
              stepCounter: "2946"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: RUNTIME_LIMIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49088"
              stepCounter: "2946"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: SEARCH_RESULTS_LIMIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49089"
              stepCounter: "2946"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: TAF_REPORT_THRESHOLD_CONFIG_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49090"
              stepCounter: "2946"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: TAF_REPORT_THRESHOLD_CONFIG_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49091"
              stepCounter: "2946"
            config: {}
            dataType: VARCHAR(3996)
            defaultValue: ""
            description: ""
            name: TAF_REPORT_THRESHOLD_CONFIG_NA
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49092"
              stepCounter: "2946"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49093"
              stepCounter: "2946"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49094"
              stepCounter: "2946"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'TAF_REPORT_THRESHOLD_CONFIGUR') }}
      name: TAF_REPORT_THRESHOLD_CONFIGUR
      schema: ""
      sqlType: Source
      table: TAF_REPORT_THRESHOLD_CONFIGUR
      type: sourceInput
    stepCounter: "2946"
