steps:
  XWS_SHIP_REROUTES-5391:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: SOURCES_ORACLE_XWS
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184951"
              stepCounter: "5391"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: SHIP_REROUTE_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184952"
              stepCounter: "5391"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184953"
              stepCounter: "5391"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: LAST_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184954"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: PROCESS_STATUS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184955"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(2000)
            defaultValue: ""
            description: ""
            name: PROCESS_MESSAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184956"
              stepCounter: "5391"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATION_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184957"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(40)
            defaultValue: ""
            description: ""
            name: TELEPHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184958"
              stepCounter: "5391"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: LAST_UPDATE_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184959"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(150)
            defaultValue: ""
            description: ""
            name: LAST_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184960"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(150)
            defaultValue: ""
            description: ""
            name: FIRST_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184961"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: STATE_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184962"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(1000)
            defaultValue: ""
            description: ""
            name: PUSH_NOTIF_MESSAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184963"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(150)
            defaultValue: ""
            description: ""
            name: COMPANY_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184964"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: CITY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184965"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(300)
            defaultValue: ""
            description: ""
            name: EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184966"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: POSTAL_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184967"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: MIDDLE_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184968"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: PUSH_NOTIF_STATUS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184969"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: ADDRESS1
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184970"
              stepCounter: "5391"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: SHIP_CONFIRM_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184971"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: ADDRESS3
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184972"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: COUNTRY_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184973"
              stepCounter: "5391"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: ADDRESS2
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184974"
              stepCounter: "5391"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184975"
              stepCounter: "5391"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'XWS_SHIP_REROUTES') }}
      name: XWS_SHIP_REROUTES
      schema: ""
      sqlType: Source
      table: XWS_SHIP_REROUTES
      type: sourceInput
    stepCounter: "5391"
