steps:
  ERP_FULFILLMENT_ROUTES-5307:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: SOURCES_ORACLE_XWS
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183680"
              stepCounter: "5307"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: FULFILLMENT_ROUTE_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183681"
              stepCounter: "5307"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183682"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: REGION_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183683"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: ROUTE_TO_WMS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183684"
              stepCounter: "5307"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: LAST_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183685"
              stepCounter: "5307"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATION_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183686"
              stepCounter: "5307"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: LAST_UPDATE_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183687"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: IS_UPGRADEABLE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183688"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: BILL_TO_VENDOR_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183689"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: IS_LINE_HAUL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183690"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(1000)
            defaultValue: ""
            description: ""
            name: DESCRIPTION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183691"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: SHIP_FROM_VENDOR_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183692"
              stepCounter: "5307"
            config: {}
            dataType: VARCHAR(80)
            defaultValue: ""
            description: ""
            name: FAMILIAR_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183693"
              stepCounter: "5307"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183694"
              stepCounter: "5307"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'ERP_FULFILLMENT_ROUTES') }}
      name: ERP_FULFILLMENT_ROUTES
      schema: ""
      sqlType: Source
      table: ERP_FULFILLMENT_ROUTES
      type: sourceInput
    stepCounter: "5307"
