steps:
  ERP_WMS_ROUTES-5376:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: SOURCES_ORACLE_XWS
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184694"
              stepCounter: "5376"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184695"
              stepCounter: "5376"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: LAST_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184696"
              stepCounter: "5376"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: SHIP_FROM_ORG_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184697"
              stepCounter: "5376"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: WMS_ROUTE_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184698"
              stepCounter: "5376"
            config: {}
            dataType: VARCHAR(80)
            defaultValue: ""
            description: ""
            name: FAMILIAR_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184699"
              stepCounter: "5376"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: CARRIER_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184700"
              stepCounter: "5376"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184701"
              stepCounter: "5376"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184702"
              stepCounter: "5376"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATION_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "184703"
              stepCounter: "5376"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: LAST_UPDATE_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'ERP_WMS_ROUTES') }}
      name: ERP_WMS_ROUTES
      schema: ""
      sqlType: Source
      table: ERP_WMS_ROUTES
      type: sourceInput
    stepCounter: "5376"
