steps:
  DFSLE_AGREEMENT_CONFIGURATION_C-4374:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_SALESFORCE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109031"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109032"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: OWNER_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109033"
              stepCounter: "4374"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: IS_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109034"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109035"
              stepCounter: "4374"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: CREATED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109036"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: CREATED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109037"
              stepCounter: "4374"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109038"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109039"
              stepCounter: "4374"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: SYSTEM_MODSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109040"
              stepCounter: "4374"
            config: {}
            dataType: DATE
            defaultValue: ""
            description: ""
            name: LAST_ACTIVITY_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109041"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_FOLDER_ID_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109042"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_SOURCE_OBJECT_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109043"
              stepCounter: "4374"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_TEMP_FOLDER_ID_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109044"
              stepCounter: "4374"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_AGREEMENT_CONFIGURATION_C') }}
      name: DFSLE_AGREEMENT_CONFIGURATION_C
      schema: ""
      sqlType: Source
      table: DFSLE_AGREEMENT_CONFIGURATION_C
      type: sourceInput
    stepCounter: "4374"
