steps:
  VAT_ONLINE_CONFIGURATION-3000:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50247"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: COUNTRY_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50248"
              stepCounter: "3000"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50249"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: HELP_TEXT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50250"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: ISMANDATORY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50251"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: ISVISIBLE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50252"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50253"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_NEW_TAX_FILING
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50254"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_NONDEDUCTIBLE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50255"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: LABEL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50256"
              stepCounter: "3000"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50257"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50258"
              stepCounter: "3000"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50259"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: PRODUCT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50260"
              stepCounter: "3000"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: SUBSIDIARY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50261"
              stepCounter: "3000"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: TAB_ORDER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50262"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TYPE_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50263"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: VALUE_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50264"
              stepCounter: "3000"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: VAT_ONLINE_CONFIGURATION_EXTID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50265"
              stepCounter: "3000"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: VAT_ONLINE_CONFIGURATION_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50266"
              stepCounter: "3000"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50267"
              stepCounter: "3000"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "50268"
              stepCounter: "3000"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'VAT_ONLINE_CONFIGURATION') }}
      name: VAT_ONLINE_CONFIGURATION
      schema: ""
      sqlType: Source
      table: VAT_ONLINE_CONFIGURATION
      type: sourceInput
    stepCounter: "3000"
