steps:
  EP_QUEUE_SETTINGS-2559:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41694"
              stepCounter: "2559"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: EP_QUEUE_SETTINGS_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41695"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: BANK_FILE_CREATION_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41696"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: BATCH_PROCESSING_DEPLOYMENT_O
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41697"
              stepCounter: "2559"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41698"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: DEFAULT_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41699"
              stepCounter: "2559"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: EP_PREFERENCE_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41700"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: EP_QUEUE_SETTINGS_EXTID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41701"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: INSTANT_PAYMENT_PROCESSING_NE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41702"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41703"
              stepCounter: "2559"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41704"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: NOTIFICATION_DEPLOYMENT_OLD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41705"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: NOTIFICATION_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41706"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: PARENT_DEPLOYMENT_OLD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41707"
              stepCounter: "2559"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41708"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(262136)
            defaultValue: ""
            description: ""
            name: PAYMENT_CREATOR_DEPLOYMENT_OL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41709"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: PAYMENT_PROCESSING_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41710"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: REMOVE_UNPROCESSED_TRANSACTIO
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41711"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: REVERSAL_DEPLOYMENT_OLD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41712"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: REVERSAL_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41713"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ROLLBACK_DEPLOYMENT_OLD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41714"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ROLLBACK_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41715"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: SCHEDULER_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41716"
              stepCounter: "2559"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TRANSACTION_MARKING_NEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41717"
              stepCounter: "2559"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41718"
              stepCounter: "2559"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41719"
              stepCounter: "2559"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'EP_QUEUE_SETTINGS') }}
      name: EP_QUEUE_SETTINGS
      schema: ""
      sqlType: Source
      table: EP_QUEUE_SETTINGS
      type: sourceInput
    stepCounter: "2559"
