steps:
  NSPB___ACCOUNT_BALANCE_CONFIG-2766:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45264"
              stepCounter: "2766"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CUBE_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45265"
              stepCounter: "2766"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45266"
              stepCounter: "2766"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DIMENSION_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45267"
              stepCounter: "2766"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45268"
              stepCounter: "2766"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45269"
              stepCounter: "2766"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: MEMBER_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45270"
              stepCounter: "2766"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: NSPB___ACCOUNT_BALANCE_CONF_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45271"
              stepCounter: "2766"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: NSPB___ACCOUNT_BALANCE_CONF_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45272"
              stepCounter: "2766"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45273"
              stepCounter: "2766"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: SHOW_IN_ACCOUNT_BALANCE_PORTL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45274"
              stepCounter: "2766"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: TYPE_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45275"
              stepCounter: "2766"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45276"
              stepCounter: "2766"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45277"
              stepCounter: "2766"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___ACCOUNT_BALANCE_CONFIG') }}
      name: NSPB___ACCOUNT_BALANCE_CONFIG
      schema: ""
      sqlType: Source
      table: NSPB___ACCOUNT_BALANCE_CONFIG
      type: sourceInput
    stepCounter: "2766"
