steps:
  DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C-4386:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_SALESFORCE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109259"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109260"
              stepCounter: "4386"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: IS_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109261"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109262"
              stepCounter: "4386"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: CREATED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109263"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: CREATED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109264"
              stepCounter: "4386"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109265"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109266"
              stepCounter: "4386"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: SYSTEM_MODSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109267"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: DFSLE_ENVELOPE_CONFIGURATION_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109268"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: DFSLE_EXTENSION_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109269"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(6000)
            defaultValue: ""
            description: ""
            name: DFSLE_FILTER_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109270"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_NAME_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109271"
              stepCounter: "4386"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_READ_ONLY_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109272"
              stepCounter: "4386"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_REQUIRED_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109273"
              stepCounter: "4386"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: DFSLE_SEQUENCE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109274"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(120)
            defaultValue: ""
            description: ""
            name: DFSLE_SOURCE_ID_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109275"
              stepCounter: "4386"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_TYPE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109276"
              stepCounter: "4386"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C') }}
      name: DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C
      schema: ""
      sqlType: Source
      table: DFSLE_ENVELOPE_CONFIGURATION_DOCUMENT_C
      type: sourceInput
    stepCounter: "4386"
