steps:
  NSPB___DATA_SOURCE_SETTINGS-4293:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107308"
              stepCounter: "4293"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: NSPB___DATA_SOURCE_SETTINGS_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107309"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ACCOUNT_TYPE_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107310"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ALTERNATE_PARENT_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107311"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ALTERNATE_SAVED_SEARCH
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107312"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CATEGORY_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107313"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DATA_SOURCE_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107314"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DATA_STORAGE_FOR_PARENT_RECOR
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107315"
              stepCounter: "4293"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107316"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: DO_NOT_USE_STANDARD_SAVED_SEA
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107317"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DUMMY_PARENT_ALIAS_AFFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107318"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DUMMY_PARENT_CHILD_AFFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107319"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: EXCLUDE_ALTERNATE_PARENT_COLU
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107320"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: EXCLUDE_UPPER_LEVEL_MEMBERS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107321"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: FILTER_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107322"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107323"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ITEM_TYPE_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107324"
              stepCounter: "4293"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107325"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: NSPB___DATA_SOURCE_SETTINGS_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107326"
              stepCounter: "4293"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107327"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: SORT_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107328"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TOP_LEVEL_PARENT_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107329"
              stepCounter: "4293"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: USE_DYNAMIC_CALC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107330"
              stepCounter: "4293"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107331"
              stepCounter: "4293"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "107332"
              stepCounter: "4293"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___DATA_SOURCE_SETTINGS') }}
      name: NSPB___DATA_SOURCE_SETTINGS
      schema: ""
      sqlType: Source
      table: NSPB___DATA_SOURCE_SETTINGS
      type: sourceInput
    stepCounter: "4293"
