steps:
  BSP_CSV_PARSER_CONFIGURATION-2432:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39596"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ACCOUNT_CLOSING_BALANCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39597"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ACCOUNT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39598"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: AMOUNT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39599"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: AMOUNT_CREDIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39600"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: AMOUNT_CURRENCY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39601"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: AMOUNT_DEBIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39602"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: AMOUNT_INDICATOR
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39603"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: BSP_CSV_PARSER_CONFIGURATIO_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39604"
              stepCounter: "2432"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: BSP_CSV_PARSER_CONFIGURATIO_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39605"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CLOSING_BALANCE_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39606"
              stepCounter: "2432"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: COLUMN_DELIMITER_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39607"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CONFIGURATION_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39608"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DATE_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39609"
              stepCounter: "2432"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39610"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DATE_FORMAT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39611"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ENTITY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39612"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ENTITY_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39613"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: FINANCIAL_INSTITUTION_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39614"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: INV_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39615"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39616"
              stepCounter: "2432"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39617"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: MEMO
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39618"
              stepCounter: "2432"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: NEGATIVE_NUMBER_FORMAT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39619"
              stepCounter: "2432"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: NUMBER_FORMAT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39620"
              stepCounter: "2432"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39621"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: PAYEE_OR_PAYER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39622"
              stepCounter: "2432"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: TEXT_QUALIFIER_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39623"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TRANSACTION_CREDIT_INDICATOR
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39624"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TRANSACTION_DEBIT_INDICATOR
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39625"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TRANSACTION_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39626"
              stepCounter: "2432"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TRANSACTION_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39627"
              stepCounter: "2432"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39628"
              stepCounter: "2432"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39629"
              stepCounter: "2432"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'BSP_CSV_PARSER_CONFIGURATION') }}
      name: BSP_CSV_PARSER_CONFIGURATION
      schema: ""
      sqlType: Source
      table: BSP_CSV_PARSER_CONFIGURATION
      type: sourceInput
    stepCounter: "2432"
