steps:
  TAF_SETUP_CONFIGURATION_FIELD-2947:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49095"
              stepCounter: "2947"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: TAF_SETUP_CONFIGURATION_FIE_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49096"
              stepCounter: "2947"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49097"
              stepCounter: "2947"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: FIELD_KEY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49098"
              stepCounter: "2947"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: FIELD_TYPE_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49099"
              stepCounter: "2947"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49100"
              stepCounter: "2947"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49101"
              stepCounter: "2947"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49102"
              stepCounter: "2947"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: REPORT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49103"
              stepCounter: "2947"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: TAF_SETUP_CONFIGURATION_FIE_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49104"
              stepCounter: "2947"
            config: {}
            dataType: VARCHAR(3996)
            defaultValue: ""
            description: ""
            name: TAF_SETUP_CONFIGURATION_FIE_NA
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49105"
              stepCounter: "2947"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49106"
              stepCounter: "2947"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "49107"
              stepCounter: "2947"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'TAF_SETUP_CONFIGURATION_FIELD') }}
      name: TAF_SETUP_CONFIGURATION_FIELD
      schema: ""
      sqlType: Source
      table: TAF_SETUP_CONFIGURATION_FIELD
      type: sourceInput
    stepCounter: "2947"
