steps:
  DFSLE_AGREEMENT_CONFIGURATION_HISTORY-4375:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_SALESFORCE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109045"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109046"
              stepCounter: "4375"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: IS_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109047"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109048"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: CREATED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109049"
              stepCounter: "4375"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: CREATED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109050"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: FIELD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109051"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(120)
            defaultValue: ""
            description: ""
            name: DATA_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109052"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: OLD_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109053"
              stepCounter: "4375"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: NEW_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109054"
              stepCounter: "4375"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_AGREEMENT_CONFIGURATION_HISTORY') }}
      name: DFSLE_AGREEMENT_CONFIGURATION_HISTORY
      schema: ""
      sqlType: Source
      table: DFSLE_AGREEMENT_CONFIGURATION_HISTORY
      type: sourceInput
    stepCounter: "4375"
