steps:
  EP_QUEUE_SETTINGS_SUBSIDIARY_MAP-2561:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41725"
              stepCounter: "2561"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: EP_QUEUE_SETTINGS_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41726"
              stepCounter: "2561"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: SUBSIDIARY_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41727"
              stepCounter: "2561"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41728"
              stepCounter: "2561"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "41729"
              stepCounter: "2561"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'EP_QUEUE_SETTINGS_SUBSIDIARY_MAP') }}
      name: EP_QUEUE_SETTINGS_SUBSIDIARY_MAP
      schema: ""
      sqlType: Source
      table: EP_QUEUE_SETTINGS_SUBSIDIARY_MAP
      type: sourceInput
    stepCounter: "2561"
