steps:
  NSPB___SAVED_SEARCH_SETTINGS-2776:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45448"
              stepCounter: "2776"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: NSPB___SAVED_SEARCH_SETTING_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45449"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ACCOUNT_TYPE_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45450"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ALTERNATE_PARENT_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45451"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ALTERNATE_SAVED_SEARCH
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45452"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CATEGORY_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45453"
              stepCounter: "2776"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45454"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: DO_NOT_USE_STANDARD_SAVED_SEA
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45455"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DUMMY_PARENT_ALIAS_AFFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45456"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DUMMY_PARENT_CHILD_AFFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45457"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: EXCLUDE_UPPER_LEVEL_MEMBERS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45458"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: FILTER_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45459"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45460"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ITEM_TYPE_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45461"
              stepCounter: "2776"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45462"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: NSPB___SAVED_SEARCH_SETTING_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45463"
              stepCounter: "2776"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45464"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: SAVED_SEARCH_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45465"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: SORT_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45466"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: TOP_LEVEL_PARENT_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45467"
              stepCounter: "2776"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: USE_DYNAMIC_CALC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45468"
              stepCounter: "2776"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45469"
              stepCounter: "2776"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45470"
              stepCounter: "2776"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'NSPB___SAVED_SEARCH_SETTINGS') }}
      name: NSPB___SAVED_SEARCH_SETTINGS
      schema: ""
      sqlType: Source
      table: NSPB___SAVED_SEARCH_SETTINGS
      type: sourceInput
    stepCounter: "2776"
