steps:
  DFSLE_ENVELOPE_CONFIGURATION_RECIPIENT_C-4388:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_SALESFORCE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109287"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109288"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: IS_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109289"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109290"
              stepCounter: "4388"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: CREATED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109291"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: CREATED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109292"
              stepCounter: "4388"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109293"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_BY_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109294"
              stepCounter: "4388"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: SYSTEM_MODSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109295"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: DFSLE_ENVELOPE_CONFIGURATION_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109296"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_ACCESS_CODE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109297"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_DELIVER_BY_SMS_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109298"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(30000)
            defaultValue: ""
            description: ""
            name: DFSLE_EMAIL_MESSAGE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109299"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(3000)
            defaultValue: ""
            description: ""
            name: DFSLE_EMAIL_SUBJECT_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109300"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_EMAIL_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109301"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(6000)
            defaultValue: ""
            description: ""
            name: DFSLE_FILTER_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109302"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(300)
            defaultValue: ""
            description: ""
            name: DFSLE_HOST_EMAIL_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109303"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(300)
            defaultValue: ""
            description: ""
            name: DFSLE_HOST_NAME_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109304"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_ID_CHECK_REQUIRED_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109305"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_INCREMENT_ROUTING_ORDER_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109306"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_IS_SENDER_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109307"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: DFSLE_LANGUAGE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109308"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(300)
            defaultValue: ""
            description: ""
            name: DFSLE_NAME_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109309"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(3000)
            defaultValue: ""
            description: ""
            name: DFSLE_NOTE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109310"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_READ_ONLY_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109311"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(393216)
            defaultValue: ""
            description: ""
            name: DFSLE_RELATIONSHIP_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109312"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_REQUIRED_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109313"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_ROLES_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109314"
              stepCounter: "4388"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: DFSLE_ROUTING_ORDER_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109315"
              stepCounter: "4388"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: DFSLE_SEQUENCE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109316"
              stepCounter: "4388"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: DFSLE_SIGN_NOW_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109317"
              stepCounter: "4388"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: DFSLE_SIGNING_GROUP_ID_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109318"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(300)
            defaultValue: ""
            description: ""
            name: DFSLE_SIGNING_GROUP_NAME_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109319"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(150)
            defaultValue: ""
            description: ""
            name: DFSLE_SMS_PHONE_NUMBER_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109320"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(54)
            defaultValue: ""
            description: ""
            name: DFSLE_SOURCE_ID_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109321"
              stepCounter: "4388"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DFSLE_TYPE_C
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "109322"
              stepCounter: "4388"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'DFSLE_ENVELOPE_CONFIGURATION_RECIPIENT_C') }}
      name: DFSLE_ENVELOPE_CONFIGURATION_RECIPIENT_C
      schema: ""
      sqlType: Source
      table: DFSLE_ENVELOPE_CONFIGURATION_RECIPIENT_C
      type: sourceInput
    stepCounter: "4388"
