steps:
  ERP_COMPLIANCE_ROUTES-5291:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: SOURCES_ORACLE_XWS
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183461"
              stepCounter: "5291"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183462"
              stepCounter: "5291"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: COMPLIANCE_ROUTE_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183463"
              stepCounter: "5291"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: LAST_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183464"
              stepCounter: "5291"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: REQUIRED_LICENSE_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183465"
              stepCounter: "5291"
            config: {}
            dataType: VARCHAR(1000)
            defaultValue: ""
            description: ""
            name: DESCRIPTION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183466"
              stepCounter: "5291"
            config: {}
            dataType: VARCHAR(80)
            defaultValue: ""
            description: ""
            name: FAMILIAR_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183467"
              stepCounter: "5291"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: REQUIRES_CONSUMER_PERMIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183468"
              stepCounter: "5291"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: REQUIRES_LICENSE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183469"
              stepCounter: "5291"
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: REQUIRES_CUSTOMER_PERMIT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183470"
              stepCounter: "5291"
            config: {}
            dataType: VARCHAR(7)
            defaultValue: ""
            description: ""
            name: DISPLAY_COLOR
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183471"
              stepCounter: "5291"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183472"
              stepCounter: "5291"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183473"
              stepCounter: "5291"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATION_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "183474"
              stepCounter: "5291"
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: LAST_UPDATE_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_ORACLE_XWS', 'ERP_COMPLIANCE_ROUTES') }}
      name: ERP_COMPLIANCE_ROUTES
      schema: ""
      sqlType: Source
      table: ERP_COMPLIANCE_ROUTES
      type: sourceInput
    stepCounter: "5291"
