steps:
  BSP_CONFIGURATION_VALUE-2427:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39547"
              stepCounter: "2427"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: BSP_CONFIGURATION_VALUE_EXTID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39548"
              stepCounter: "2427"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: BSP_CONFIGURATION_VALUE_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39549"
              stepCounter: "2427"
            config: {}
            dataType: VARCHAR(3996)
            defaultValue: ""
            description: ""
            name: BSP_CONFIGURATION_VALUE_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39550"
              stepCounter: "2427"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CONFIG_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39551"
              stepCounter: "2427"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39552"
              stepCounter: "2427"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: FORMAT_PROFILE_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39553"
              stepCounter: "2427"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39554"
              stepCounter: "2427"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39555"
              stepCounter: "2427"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39556"
              stepCounter: "2427"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: PARSER_PLUGIN_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39557"
              stepCounter: "2427"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39558"
              stepCounter: "2427"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "39559"
              stepCounter: "2427"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'BSP_CONFIGURATION_VALUE') }}
      name: BSP_CONFIGURATION_VALUE
      schema: ""
      sqlType: Source
      table: BSP_CONFIGURATION_VALUE
      type: sourceInput
    stepCounter: "2427"
