steps:
  ONLINE_FILING_CONFIGURATION-2782:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45544"
              stepCounter: "2782"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: ONLINE_FILING_CONFIGURATION_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45545"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: CONFIGURATION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45546"
              stepCounter: "2782"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45547"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_FOR_TEST
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45548"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45549"
              stepCounter: "2782"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45550"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: NEXUS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45551"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: ONLINE_FILING_CONFIGURATION_EX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45552"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(3996)
            defaultValue: ""
            description: ""
            name: ONLINE_FILING_CONFIGURATION_NA
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45553"
              stepCounter: "2782"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45554"
              stepCounter: "2782"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: PROCESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45555"
              stepCounter: "2782"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45556"
              stepCounter: "2782"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "45557"
              stepCounter: "2782"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'ONLINE_FILING_CONFIGURATION') }}
      name: ONLINE_FILING_CONFIGURATION
      schema: ""
      sqlType: Source
      table: ONLINE_FILING_CONFIGURATION
      type: sourceInput
    stepCounter: "2782"
