steps:
  STC_CONFIG_FIELDS-2911:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_NETSUITE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48374"
              stepCounter: "2911"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_CREATED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48375"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: DEFAULT_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48376"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(262136)
            defaultValue: ""
            description: ""
            name: DESCRIPTION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48377"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(262136)
            defaultValue: ""
            description: ""
            name: HELP_TEXT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48378"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(16000)
            defaultValue: ""
            description: ""
            name: ID_0
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48379"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: IS_INACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48380"
              stepCounter: "2911"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: LAST_MODIFIED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48381"
              stepCounter: "2911"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: PARENT_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48382"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(1020)
            defaultValue: ""
            description: ""
            name: STC_CONFIG_FIELDS_EXTID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48383"
              stepCounter: "2911"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: STC_CONFIG_FIELDS_ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48384"
              stepCounter: "2911"
            config: {}
            dataType: VARCHAR(3996)
            defaultValue: ""
            description: ""
            name: STC_CONFIG_FIELDS_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48385"
              stepCounter: "2911"
            config: {}
            dataType: FLOAT
            defaultValue: ""
            description: ""
            name: TYPE_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48386"
              stepCounter: "2911"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48387"
              stepCounter: "2911"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: DATE_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "48388"
              stepCounter: "2911"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_NETSUITE', 'STC_CONFIG_FIELDS') }}
      name: STC_CONFIG_FIELDS
      schema: ""
      sqlType: Source
      table: STC_CONFIG_FIELDS
      type: sourceInput
    stepCounter: "2911"
