steps:
  FISCAL_YEAR_SETTINGS-4438:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SOURCES_SALESFORCE
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110283"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: ID
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110284"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(18)
            defaultValue: ""
            description: ""
            name: PERIOD_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110285"
              stepCounter: "4438"
            config: {}
            dataType: DATE
            defaultValue: ""
            description: ""
            name: START_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110286"
              stepCounter: "4438"
            config: {}
            dataType: DATE
            defaultValue: ""
            description: ""
            name: END_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110287"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(240)
            defaultValue: ""
            description: ""
            name: NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110288"
              stepCounter: "4438"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: IS_STANDARD_YEAR
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110289"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(120)
            defaultValue: ""
            description: ""
            name: YEAR_TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110290"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(120)
            defaultValue: ""
            description: ""
            name: QUARTER_LABEL_SCHEME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110291"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(120)
            defaultValue: ""
            description: ""
            name: PERIOD_LABEL_SCHEME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110292"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(120)
            defaultValue: ""
            description: ""
            name: WEEK_LABEL_SCHEME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110293"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: QUARTER_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110294"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: PERIOD_PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110295"
              stepCounter: "4438"
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: WEEK_START_DAY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110296"
              stepCounter: "4438"
            config: {}
            dataType: VARCHAR(765)
            defaultValue: ""
            description: ""
            name: DESCRIPTION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110297"
              stepCounter: "4438"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: SYSTEM_MODSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110298"
              stepCounter: "4438"
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: _FIVETRAN_DELETED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: "110299"
              stepCounter: "4438"
            config: {}
            dataType: TIMESTAMP_TZ(9)
            defaultValue: ""
            description: ""
            name: _FIVETRAN_SYNCED
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SOURCES_SALESFORCE', 'FISCAL_YEAR_SETTINGS') }}
      name: FISCAL_YEAR_SETTINGS
      schema: ""
      sqlType: Source
      table: FISCAL_YEAR_SETTINGS
      type: sourceInput
    stepCounter: "4438"
